---
# tasks file for ansible-mongo-db-restore
- name: COPY THE FOLDER localhost server to MONGO
  copy:
    src: "{{ SOURCE_FILE_LOCATION }}"
    dest: "{{ DEST_FILE_LOCATION }}"
    remote_src: yes

- name: RESTORE THE MONGo DOCUMENTS
  shell:  "mongorestore --host={{ MONGO_USERNAME }} --gzip --port={{ MONGO_PORT }} --username={{ MONGO_USERNAME }} --db={{ MONGO_DBNAME }} --password={{ MONGO_PASSWORD }} {{ MONGO_DIR }}"
  register: _RESTORE_RESULT
  when: MONGO_RESTORE_FROM_REMOTE_SERVER

- name: DEBUG THE RESULT
  debug:
    msg: "{{ _RESTORE_RESULT }}"
  when: MONGO_RESTORE_FROM_REMOTE_SERVER

- name: RESTORE THE MONGo DOCUMENTS
  shell:  "mongorestore --gzip --db={{ MONGO_DBNAME }} --username={{ MONGO_USERNAME }}  --password={{ MONGO_PASSWORD }} {{ MONGO_DIR }}"   
  register: _RESTORE_LOCALHOST_RESULT
  when: MONGO_RESTORE_FROM_LOCALHOST_SERVER

- name: DEBUG THE RESULT
  debug:
    msg: "{{ _RESTORE_LOCALHOST_RESULT }}"
  when: MONGO_RESTORE_FROM_LOCALHOST_SERVER
